server:
   port: 80

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1/c81-s3-pyc-blog?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver 
